import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Nunito_Sans } from "next/font/google";
// import "./globals.css";
import Navbar from "@/components/Nav";
import SideNav from "@/components/SideNav";
import TopNav from "@/components/TopNav";

const nunito = Nunito_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "LokaTalent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedIn = false; // Replace with actual authentication logic
  return (
    <html lang="en">
      {!loggedIn && (
        <body className={nunito.className}>
          <Navbar />
          {children}
        </body>
      )}
    </html>
  );
}
